src/Entity/Idea.php
<?php

namespace App\Entity;

use App\Repository\IdeaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=IdeaRepository::class)
 */
class Idea
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250, nullable=false)
     * @Assert\NotBlank(message="Veuillez entrer un titre.")
     * @Assert\Length(
     *      min = 1,
     *      max = 250,
     *      minMessage = "Vous devez rentrer au moins {{ limit }} caractères.",
     *      maxMessage = "Vous ne pouvez pas rentrer plus de {{ limit }} caractères."
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank(message="Veuillez entrer une description.")
     * @Assert\Length(
     *      min = 1,
     *      max = 255,
     *      minMessage = "Vous devez rentrer au moins {{ limit }} caractères.",
     *      maxMessage = "Vous ne pouvez pas rentrer plus de {{ limit }} caractères."
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank(message="Veuillez entrer un nom d'auteur.")
     * @Assert\Length(
     *      min = 1,
     *      max = 255,
     *      minMessage = "Vous devez rentrer au moins {{ limit }} caractères.",
     *      maxMessage = "Vous ne pouvez pas rentrer plus de {{ limit }} caractères."
     * )
     */
    private $author;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    private $dateCreated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(?string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(?\DateTimeInterface $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="ideas")
     */

    private $Category;

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->Category;
    }

    /**
     * @param mixed $Category
     */
    public function setCategory($Category): void
    {
        $this->Category = $Category;
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController {

    /**
     * @Route("/", name="index")
     **/

    public function index() {
        return $this->render("default/home.html.twig");
    }

    /**
     * @Route("/about-us", name="about-us")
     **/

    public function about() {
        return $this->render("default/about.html.twig");
    }

}

templates/default/about.html.twig
<body>
    <div class="container">
        <header>
            {% include('header.html.twig') %}
        </header>

        <main>
            <p>
                Lorem ipsum dolor sit amet. Est consequatur dolor aut quod autem et velit ducimus est magni ipsam. Aut doloribus fuga non molestiae aliquid At placeat consequuntur? Ut natus nesciunt eum veritatis minus ut temporibus quibusdam sed blanditiis pariatur aut maxime deserunt et debitis dolorem in aliquam consequuntur. Et labore internos vel nobis aspernatur qui labore nihil ut omnis consequatur est omnis inventore et consectetur eaque est cupiditate impedit!

                Et eaque labore eum exercitationem consectetur id voluptatem voluptas ex deleniti natus hic mollitia quae qui error consequatur. Vel neque libero id inventore mollitia eum numquam repellendus aut omnis voluptatem. Et odit dolorum est excepturi laboriosam non earum laudantium ex corrupti voluptas qui dolores quod. Et laborum galisum ab quia dicta et cumque unde qui internos illo sed animi suscipit.

                Aut dolor recusandae id quis mollitia qui autem saepe ab rerum accusamus. Sed iure rerum et voluptas assumenda et Quis quas ut recusandae aut voluptatem cupiditate? Et incidunt optio aut rerum autem id enim ipsam. Aut consequatur distinctio eos fugit officiis aut impedit expedita sed facere explicabo.
            </p>
        </main>

        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </div>
</body>

templates/default/add.html.twig
<body>
    <div class="container">
        <header>
            {% include('header.html.twig') %}
        </header>

        <main>
            <h1>Ajouter une idée</h1>

            <p/>

            {{ form_start(ideaForm) }}
            {{ form_row(ideaForm.title) }}
            {{ form_row(ideaForm.description) }}
            {{ form_row(ideaForm.author, {'value' : app.user.getUsername() }) }}
            {{ form_row(ideaForm.category) }}

            <p/>

            <button type="submit" class="btn btn-success">Ajouter</button>

            {{ form_end(ideaForm) }}
        </main>

        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </div>
</body>

templates/default/detail.html.twig
<body>
    <div class="container">
        <header>
            {% include('header.html.twig') %}
        </header>

        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        <main>
            <h1>{{ idea.title }}</h1>

            {{ idea.Category.name }}

            <p/>
            <div class="container">
                {{ idea.description }}
            </div>
            <p/>
            {{ idea.author }} - {{ idea.dateCreated | date('d/m/Y') }}
        </main>

        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </div>
</body>

templates/default/home.html.twig
<body>
    <div class="container">
        <header>
            {% include('header.html.twig') %}
        </header>

        <main>
            <h1>Welcome to Bucket-List!</h1>

            <p>Lorem ipsum dolor sit amet. Ut molestiae mollitia sed eius dolorem rem laboriosam autem sed unde modi. Qui quam facilis et voluptatum quibusdam eos inventore minus vel vero distinctio sit error dolorem et officia neque est quam aperiam. Aut iste reprehenderit vel temporibus aliquam qui nostrum eveniet id rerum itaque rem autem amet. Est sint corrupti ut porro rerum et aliquid nemo.</p>
        </main>

        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </div>
</body>

templates/default/list.html.twig
<body>
    <div class="container">
        <header>
            {% include('header.html.twig') %}
        </header>

        <main>
            {% for idea in ideas %}
                <div>
                    <a href="{{ path('detail', {'id': idea.id}) }}"> {{ idea.title }}</a>
                    -
                    <a href="{{ path('idea_edit', {'id': idea.id}) }}">Modifier</a>
                </div>
            {% endfor %}
        </main>

        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </div>
</body>